SELECT PRODUCT.PRODUCT_CODE, (
    SUM(PRODUCT.PRICE * SALE.SALES_AMOUNT)
) AS SALES
FROM PRODUCT AS PRODUCT
INNER JOIN OFFLINE_SALE AS SALE
ON PRODUCT.PRODUCT_ID = SALE.PRODUCT_ID
GROUP BY PRODUCT.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT.PRODUCT_CODE ASC;