SELECT TOPS.NAME, TOPS.DATETIME
FROM (
    SELECT INS.NAME, INS.DATETIME, DATEDIFF(CURDATE(), INS.DATETIME) AS DIFF
    FROM ANIMAL_INS INS
    LEFT JOIN ANIMAL_OUTS OUTS
    ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
    WHERE OUTS.DATETIME IS NULL
    ORDER BY DIFF DESC
    LIMIT 3
) AS TOPS
ORDER BY TOPS.DATETIME ASC;