SELECT CHILD.ID, CHILD.GENOTYPE, PARENT.GENOTYPE AS PARENT_GENOTYPE FROM ECOLI_DATA CHILD, ECOLI_DATA PARENT
WHERE CHILD.PARENT_ID = PARENT.ID
    AND PARENT.GENOTYPE & CHILD.GENOTYPE = PARENT.GENOTYPE
ORDER BY CHILD.ID ASC;